 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: 
           name: Restore Packages
           command: dotnet restore
       - run: 
           name: Build Application
           command: dotnet build
       - run: 
           name: Unit Tests
           command: dotnet test
